[www]                                           ; pool name, must match the filename (www.conf)
user = www-data                                 ; system user that runs PHP-FPM processes
group = www-data                                ; system group that runs PHP-FPM processes

listen = 0.0.0.0:9000                           ; listens on all network interfaces (0.0.0.0) on port 9000b

pm = dynamic                                    ; process manager mode: dynamically adjusts child processes
pm.max_children = 5                             ; max PHP processes running simultaneously
pm.start_servers = 2                            ; how many processes to start initially
pm.min_spare_servers = 1                        ; minimum idle processes kept in reserve
pm.max_spare_servers = 3                        ; maximum idle processes kept in reserve

request_terminate_timeout = 60s                 ; kills any PHP script that runs longer than 60 seconds
                                                ; prevents a stuck script from hanging the server forever
security.limit_extensions = .php                ; only execute files with .php extension
                                                ; prevents someone from uploading a .txt with PHP code and running it
clear_env = no                                  ; keeps environment variables available for PHP scripts
                                                ; needed so WordPress can access $MYSQL_HOST, $WP_URL, etc.